#cloud-config
users:
  - name: root
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
package_update: true
package_upgrade: true
packages:
  - nginx
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo "<!doctype html>
          <html>
           <head>
              <title>TeleClinic static application</title>
           </head>
            <body>
              <p>This is the super complicated, state of the art application developed by
                 the TeleClinic engineering teams!
              </p>
            </body>
          </html>" | sudo tee > /var/www/html/index.html
